create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  category text not null default 'Operating Expenses',
  amount numeric not null default 0,
  date date not null default current_date,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.expenses enable row level security;

create policy if not exists expenses_select_own
  on public.expenses
  for select
  using (auth.uid() = user_id);

create policy if not exists expenses_insert_own
  on public.expenses
  for insert
  with check (auth.uid() = user_id);

create policy if not exists expenses_update_own
  on public.expenses
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy if not exists expenses_delete_own
  on public.expenses
  for delete
  using (auth.uid() = user_id);
